# Generated by Django 5.0.7 on 2026-08-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdCounter',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('next_value', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='CodeSequence',
        ),
    ]
