# Generated by Django 5.0.7 on 2026-08-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_idcounter_delete_codesequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='event_id',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
    ]
